### PR TITLE
fix travis, merge open PRs

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by graingert** [comment]
@btimby ^

**Comment by btimby** [comment]
Thanks for all of the work! I gave it a quick look and I don't have any concerns. I will review later and merge unless I find something.

**Comment by graingert** [comment]
@btimby ok great stuff - any update on this?

**Review by btimby — APPROVED** [review]
Thanks again.

**Comment by graingert** [comment]
@btimby can we get a release?

**Comment by graingert** [comment]
@btimby is there any chance of a new release?

**Comment by graingert** [comment]
@btimby is there any chance of a new release?

**Comment by graingert** [comment]
@btimby is there any chance of a new release?

**Pull request merged**
